services:
  api:
    build: .
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    ports:
      - "8000:8000"
    environment:
      - CHECK_PATH=/app
      - REDIS_HOST=redis-db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis-db

  redis-db:
    image: redis:8-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  redis_data:
